import type { Metadata } from "next";
import { Onest } from 'next/font/google';
import "./globals.css";

const onest = Onest({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    variable: '--font-onest',
});


export const metadata: Metadata = {
  title: "GetShopTV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${onest.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
